extends: airbnb-base
env:
  node: true
  mocha: true
plugins:
  - import
  - flowtype
parser: babel-eslint
rules:
  no-console: 0
  import/no-extraneous-dependencies: 0
  quote-props: 0
  comma-dangle: ["error", "never"]
  flowtype/require-valid-file-annotation: 2
  flowtype/space-after-type-colon: 2
  flowtype/require-return-type:
    - 1
    - always
    - excludeArrowFunctions: true
